name: travel_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  curved_navigation_bar: ^1.0.3
  http: ^1.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.10
  calendar_date_picker2: ^0.5.5
  toggle_switch: ^2.3.0 
  url_launcher: ^6.2.6
  maps_launcher: ^2.0.7

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
   
  
  

