// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_OkDtruB2JLgpvkrSxfW0yq8OQl5pxfk',
    appId: '1:595524240990:web:a107dedfb8def7ee1d96cf',
    messagingSenderId: '595524240990',
    projectId: 'travel-companion-ac334',
    authDomain: 'travel-companion-ac334.firebaseapp.com',
    storageBucket: 'travel-companion-ac334.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7SexieloUdAWzvyiMIJ8YpYJqUPaa6o',
    appId: '1:595524240990:android:fcdf1431285b65501d96cf',
    messagingSenderId: '595524240990',
    projectId: 'travel-companion-ac334',
    storageBucket: 'travel-companion-ac334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATA5oyUxkBTeW3wUzyOFHYDZnnnd6J3o',
    appId: '1:595524240990:ios:248479b97429d6af1d96cf',
    messagingSenderId: '595524240990',
    projectId: 'travel-companion-ac334',
    storageBucket: 'travel-companion-ac334.appspot.com',
    iosBundleId: 'com.example.travelCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBATA5oyUxkBTeW3wUzyOFHYDZnnnd6J3o',
    appId: '1:595524240990:ios:fa38bf4a3254b2111d96cf',
    messagingSenderId: '595524240990',
    projectId: 'travel-companion-ac334',
    storageBucket: 'travel-companion-ac334.appspot.com',
    iosBundleId: 'com.example.travelCompanion.RunnerTests',
  );
}
